### ISSUE TITLE
Deal with scattered .gitignore files

### ISSUE THREAD

**Issue by onkoe** [Sooner-Rover-Team/SoonerRoverTeamV#31]
### wait what
As-is, there are a lot of .gitignore files just floating around in subdirectories. While git accepts these as normal .gitignore files, and will still read them when it finds them, git has some [special rules](https://git-scm.com/docs/gitignore). Of these, it's most important that the .gitignore in the parent folders overrides those in child folders. Which is **scary**, and **could result in data loss**...

### how do you plan to fix it? 
I was going to dump all of these .gitignores into the root of the repo, as git suggests. Since we plan to have [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), though, it wouldn't make sense to move them, then rewrite them when these inner projects become submodules. 

### so..? 
However, if we make larger repos for many projects e.g. _Sooner-Rover-Team/Autonomous_ or _Sooner-Rover-Team/Mission-Control_, it makes sense to wait and see, as we'll still end up combining the .gitignore files anyways.

### Tasks: 
- [ ] Break the giant repo into smaller repos
- [ ] Remove .gitignore files from subdirectories
- [ ] Fuse the old .gitignore files into larger ones
- [ ] Stop worrying about data loss
- [x] Party
